name: "DEV deployment"

concurrency: "1"

on: [push]

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: wwi_dab
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest
    environment: dev

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle run wwi_dab_job --refresh-all
        working-directory: wwi_dab
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
